version: "3.3"

services:
  db:
    image: mysql
    restart: always
    env_file: ./.env
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: $MYSQL_DATABASE
    ports: 
      - 3306:3306
    volumes: 
      - db-config:/var/lib/mysql
    network_mode: host
  app:
    build: './'
    image: node-mysql-app
    expose:
      - 8080
    ports:
      - 8080:8080
    restart: always
    depends_on: 
      - db
    network_mode: host
volumes: 
  db-config:
